### ISSUE TITLE
Needs mode for Master & Slave on single channel

### ISSUE THREAD

**Issue by timreyes** [saleae/modbus-analyzer#2]
Specifically, we should have a combined mode, called "Modbus/RTU - Master & Slave", which auto-detects the messages on a single data line as either Master or Slave. Modbus can have both Master & Slave messages on a single line.

The simplest solution is to try both decodings modes (master and slave) for each decoded frame (single blue decoded box) – the correct one for is the one with a valid Checksum.

**Comment by david-vankampen** [comment]
I believe this should be mostly addressed in #3 - I had issues using the failing checksum, so I just added a flag indicating whether it was processing a request or a response.

**Comment by timreyes** [comment]
The same issue might have been reported here too:
https://discuss.saleae.com/t/modbus-analyzer/2024/2

**Comment by ghost** [comment]
@timreyes & @david-vankampen 

Is there a fix for this yet? I am working with modbus and have no way to see the response from a device. Every message is considered a Server or Client. You need both call and response to properly understand what is happening on the bus.

Notice the "invalid checksum" in the attached image. The analysis on the Saleae's part is incorrect  because the server is actually responding properly with a valid checksum. (CRC-16 assumed)

[RTU]>Tx > 15:01:56:189 - 01  03  00  80  00  02  C5  E3  
[RTU]>Rx > 15:01:56:205 - 01  03  04  0D  F2  07  BC  5A  ED  

![image](https://github.com/saleae/modbus-analyzer/assets/135625062/de2139af-57b6-4ad0-9b46-1f014691f165)

**Comment by david-vankampen** [comment]
@sgal-powerbreezer it looks like #3 is still pending.  I will bump that one.

**Comment by ghost** [comment]
thank you🙏

**Comment by timreyes** [comment]
Issue report from internal ticket # 91516.

"It’s the modbus analyzer not being able to differentiate between when data is being requested/received which gives a Checksum error.

So what happens in first instance is data is requested by Master which the Modbus Analyzer reads correctly. Second instance is then the slave sends back the data and Master receives it but Modbus Analyzer gives CheckSum error even with 2 Modbus Analyser (Client + Server) selected for one data line, because it isn’t able to differentiate between the 2 it reads it wrong. Other people have had same issue in the past and in that post there was one custom analyzer called (Modbus Client + Server) which would differentiate between the 2 and apply Client/Server settings depending on whether the data was being requested or received.

Ill attach a screenshot to show you further:
![image001](https://github.com/user-attachments/assets/07419a8c-a4f7-4b38-830f-df5668265101)

So, as you can see above Modbus in Red is Client and one in brown is Server. The first pack of data is read correctly suing Modbus Client as Master is requesting data. In second pack data is being received which should be read correctly using Modbus Server this time but because it follows the first pack incorrectly it reads the second pack incorrectly as well."

---

"Furthermore, I will also attach the .sal file for further reference and to be used in the comment you post."
[LA - Session 1.sal.zip](https://github.com/user-attachments/files/17262593/LA.-.Session.1.sal.zip)

**Comment by SysMan-One** [comment]
Hello!
Is the issue has been resolved ?

I have the same problem:
https://github.com/saleae/modbus-analyzer/issues/2#issuecomment-2394355360

**Comment by timreyes** [comment]
@SysMan-One This issue is still in the Open status, and we haven't had a chance to look into this unfortunately, mainly due to other large scale priority projects we've been working on.
